uploads = []
generated = []

[[outputs]]
id = "Gjl7J39lmwhE5YadUDZQ1"
uri = "file://drop_offs.csv"
type = "table"
title = "466 Drop-offs — Name, Phone, Email, Vehicle, Date"

[[outputs]]
id = "iAPwQOr7o4gxB10NBRhAz"
uri = "file://true_dropoffs.csv"
type = "table"
title = "187 True Drop-offs — Not in CRM"

[[outputs]]
id = "4-b-UnWjUhiFl7RVI1k-U"
uri = "file://dropoffs.csv"
type = "table"
title = "325 Drop-off Leads — Click to Download"

[[outputs]]
id = "ntM97kE3DvRymlgLtFegd"
uri = "file://dropped-leads-last-7-days.csv"
type = "table"
title = "Dropped Leads — Last 7 Days (198 unique numbers)"
